version: "3.8"

services:
    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/html:rw
            - ./nginx/log:/var/log/nginx
        restart: unless-stopped
        depends_on:
            - php
            - mysql
        networks:
            - backend_net

    mysql:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: wp
            MYSQL_USER: wp
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - ./mysql:/var/lib/mysql
            # - ./backup:/backup
        restart: unless-stopped
        networks:
            - backend_net

    php:
        build:
            context: .
            # custome image including composer
            dockerfile: php.dockerfile
        volumes:
            - ./src:/var/www/html:rw
        restart: always
        depends_on:
            - mysql
        networks:
            - backend_net

    phpmyadmin:
        image: phpmyadmin:latest
        depends_on:
            - mysql
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysql
            MYSQL_USER: wp
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            # PMA_ABSOLUTE_URI: 127.0.0.1/pma
        networks:
            - backend_net

    mailcatcher-smtp:
        build:
            context: .
            dockerfile: mailcatcher.dockerfile
        ports:
            - "1025:1025"
            - "1080:1080"
        networks:
            - backend_net

networks:
    backend_net:
        name: backend_net
